import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/SessionProvider";
import AntiCapture from "@/components/AntiCapture"; 
import GlobalWatermark from "@/components/GlobalWatermark";
import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ml-80px md:ml-[220px]  text-white`}>
        
        <NextAuthProvider>
          <AntiCapture /> 
          <Providers> 
          {children}
          </Providers>
        </NextAuthProvider>
        
      </body>
    </html>
  );
}